### ISSUE TITLE
Success field

### ISSUE THREAD

**Issue by ericecook** [icook/yota#7]
Only works with ajax fields - text hard coded

**Comment by icook** [comment]
The reasoning behind only working with AJAX fields is that in most conventional submission cases you won't be re-rendering the form if the data is valid, frequently you're redirecting them and setting a flash message of some kind. However I agree that for the example it seems a bit missing, I'll probably add something simple outside of the form render to ack submission.

For AJAX I was torn. I felt like the coolest way to build it would be something like trying to have the error header generate (https://github.com/icook/yota/blob/master/src/yota/__init__.py#L205) create a notification aimed at the start node, but for now I tacked together that solution. I figured if they wanted to change the message they could do so programatically, but I think the root of the problem is that there should be some way to feed information to the success callback because sometimes all validations might pass, but there was a database error... Just some thoughts.

**Comment by ericecook** [comment]
Yea in non-ajax use it 90% of the time it won't be necessary to show success, but sometimes it certainly would be useful. I also considered creating a success node, but I'm not sure it'd ever be used outside the header

I like the idea of being able to pass info into the success callback, would come in handy.

**Comment by icook** [comment]
This is now available with the Form.success_header_generate functionality.
