### ISSUE TITLE
Add several other default templates

### ISSUE THREAD

**Issue by ericecook** [icook/yota#9]
select/optionbox
checkboxs
radiobuttons

**Comment by ericecook** [comment]
8aa5529072dd1107d76df75aa51bff80ec0a1294

**Comment by icook** [comment]
This template will not work for checkboxes fyi. Some sort of data resolver will have to run.

**Comment by ericecook** [comment]
Not really...I just forgot to add a value field.

**Comment by icook** [comment]
Checkboxes need separate names which this template does not provide option for. With separate names comes the need for custom data resolution. Also I think the html attribute for checking a checkbox is `checked` instead of `selected`, so that part would need to be different. If you want I can make the checkbox one since trying to mash them together seems unnecessary.

**Comment by ericecook** [comment]
Good catch, I didn't think about that.
